### ISSUE TITLE
Does APIs.json also support JSON (Hyper) Schema?

### ISSUE THREAD

**Issue by kinlane** [apis-json/api-json#49]
http://json-schema.org/

**Comment by KiaraGrouwstra** [comment]
If this thread is about "could we make a JSON schema describing the apis.json format", +1 for that. :)
If the question is "could JSON schema be used to describe the apis.json format", I'm thinking yes.

If it might help, you could try using [this tool](http://jsonschema.net/#/) to generate a JSON schema (v4) from an example (say, the one listed [here](http://apisjson.org/format.html)) so as to get a good base to further tweak from. They also have some options there that allow customizing how many restrictions it tries to infer from the example. Tools like this are less good at some other things though, like centralizing common abstractions into global definitions pointed to from elsewhere using `$ref`.

**Comment by philsturgeon** [comment]
It looks like you can point people to some JSON Schema, just like you can point them to OpenAPI or RAML, so I think that does it, because JSON Hyper-Schema is just some extra keywords in the schema. No need for special support IMO

**Comment by kinlane** [comment]
I will add "JSON Hyper-Schema" to the list of properties for next release.

**Comment by philsturgeon** [comment]
I'm not sure you need to though. You just give it a JSON Schema url which you already support. 
<img width="545" alt="image" src="https://github.com/apis-json/api-json/assets/67381/9440bfcc-bf93-4aee-ae20-938b638ec0ee">

**Comment by kinlane** [comment]
OK then....
